package com.rejowan.numberconverter.ui.theme

import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF64568F)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFE8DDFF)
val onPrimaryContainerLight = Color(0xFF1F1048)
val secondaryLight = Color(0xFF615B71)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFE7DEF8)
val onSecondaryContainerLight = Color(0xFF1D192B)
val tertiaryLight = Color(0xFF64568F)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFE8DDFF)
val onTertiaryContainerLight = Color(0xFF1F1048)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFFDF7FF)
val onBackgroundLight = Color(0xFF1C1B20)
val surfaceLight = Color(0xFFFDF7FF)
val onSurfaceLight = Color(0xFF1C1B20)
val surfaceVariantLight = Color(0xFFE6E0EC)
val onSurfaceVariantLight = Color(0xFF48454E)
val outlineLight = Color(0xFF79757F)
val outlineVariantLight = Color(0xFFCAC4CF)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF322F35)
val inverseOnSurfaceLight = Color(0xFFF5EFF7)
val inversePrimaryLight = Color(0xFFCEBDFF)


val primaryDark = Color(0xFFCEBDFF)
val onPrimaryDark = Color(0xFF35275E)
val primaryContainerDark = Color(0xFF4B3E76)
val onPrimaryContainerDark = Color(0xFFE8DDFF)
val secondaryDark = Color(0xFFCBC3DC)
val onSecondaryDark = Color(0xFF322E41)
val secondaryContainerDark = Color(0xFF494458)
val onSecondaryContainerDark = Color(0xFFE7DEF8)
val tertiaryDark = Color(0xFFCEBDFF)
val onTertiaryDark = Color(0xFF35275E)
val tertiaryContainerDark = Color(0xFF4B3E76)
val onTertiaryContainerDark = Color(0xFFE8DDFF)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF141318)
val onBackgroundDark = Color(0xFFE6E1E9)
val surfaceDark = Color(0xFF141318)
val onSurfaceDark = Color(0xFFE6E1E9)
val surfaceVariantDark = Color(0xFF48454E)
val onSurfaceVariantDark = Color(0xFFCAC4CF)
val outlineDark = Color(0xFF938F99)
val outlineVariantDark = Color(0xFF48454E)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE6E1E9)
val inverseOnSurfaceDark = Color(0xFF322F35)
val inversePrimaryDark = Color(0xFF64568F)

